---
version: "3.9"

services:
  kode-core:
    user: app:app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kode-core
    hostname: kode-core
    restart: unless-stopped
    env_file:
      - ../src/.env
    command: >
      sh -c " alembic -c src/alembic.ini upgrade head &&
             alembic -c src/alembic.ini stamp head &&
             python src/main.py"
    networks:
      - home
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.16-alpine3.18
    hostname: kode-db
    container_name: kode-db
    restart: unless-stopped
    ports:
      - 127.0.0.1:5435:5435
    expose:
      - 5435
    env_file:
      - ../src/.env
    environment:
      PGDATA: /var/lib/postgresql/data/kode/pgdata/ 
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - apgdata:/var/lib/postgresql/data/kode/pgdata/
    networks:
      - home
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"


networks:
  home: {}
volumes:
  apgdata: {}
