---
version: "3.9"

services:
  kode-core-tests:
    user: app:app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kode-core-tests
    hostname: kode-core-tests
    restart: unless-stopped
    env_file:
      - ../src/.env.tests
    command: >
      sh -c " alembic -c src/alembic.ini upgrade head &&
             alembic -c src/alembic.ini stamp head &&
             python src/main.py"
    networks:
      - home_tests
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    depends_on:
      db-tests:
        condition: service_healthy

  db-tests:
    image: postgres:12.16-alpine3.18
    hostname: kode-db-tests
    container_name: kode-db-tests
    restart: unless-stopped
    ports:
      - 127.0.0.1:5435:5435
    expose:
      - 5435
    env_file:
      - ../src/.env.tests
    environment:
      POSTGRES_DB: tests_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - home_tests
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tests_db"]
      interval: 30s
      timeout: 30s
      retries: 3


networks:
  home_tests: {}
